UPDATE cliente
SET criado_em = CURRENT_TIMESTAMP
WHERE criado_em IS NULL;

ALTER TABLE cliente
    ALTER COLUMN criado_em SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN criado_em SET NOT NULL,
    ALTER COLUMN ativo SET DEFAULT TRUE;

UPDATE material
SET criado_em = CURRENT_TIMESTAMP
WHERE criado_em IS NULL;

ALTER TABLE material
    ALTER COLUMN criado_em SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN criado_em SET NOT NULL;

ALTER TABLE fornecedor
    ALTER COLUMN ativo SET DEFAULT TRUE;
